# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('tipo', models.IntegerField(blank=True, default=0, null=True)),
                ('descripcion', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('titular', models.IntegerField(blank=True, default=0, null=True)),
                ('apellido', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('numero', models.IntegerField(blank=True, default=None, null=True)),
                ('piso', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('depto', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('barrio', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('localidad', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('lp', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('provincia', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('empresas', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('telefono_alternativo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fecha_nacimiento', models.IntegerField(blank=True, default=None, null=True)),
                ('fecha_alta', models.IntegerField(blank=True, default=None, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, default=None, max_length=1, null=True)),
            ],
        ),
    ]
