# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titular',
            old_name='barrio',
            new_name='domicilio_barrio',
        ),
        migrations.RenameField(
            model_name='titular',
            old_name='depto',
            new_name='domicilio_calle',
        ),
        migrations.RenameField(
            model_name='titular',
            old_name='piso',
            new_name='domicilio_depto',
        ),
        migrations.RenameField(
            model_name='titular',
            old_name='numero',
            new_name='domicilio_numero',
        ),
        migrations.AddField(
            model_name='titular',
            name='domicilio_laboral_barrio',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='titular',
            name='domicilio_laboral_calle',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='titular',
            name='domicilio_laboral_codigo_postal',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='titular',
            name='domicilio_laboral_depto',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='titular',
            name='domicilio_laboral_localidad',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='titular',
            name='domicilio_laboral_lp',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='titular',
            name='domicilio_laboral_numero',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='titular',
            name='domicilio_laboral_piso',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='titular',
            name='domicilio_laboral_provincia',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='titular',
            name='domicilio_laboral_telefono',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='titular',
            name='domicilio_piso',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
