# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_auto_20180824_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titular',
            name='domicilio_barrio',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
