# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_auto_20180824_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titular',
            name='tipo',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='titular',
            name='titular',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
