# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-25 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0005_contactonormalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactonormalizado',
            name='tipo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contactonormalizado',
            name='titular',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='contactonormalizado',
            unique_together=set([('tipo', 'titular')]),
        ),
    ]
