# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-25 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0006_auto_20180825_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactonormalizado',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='normalizador.Barrio'),
        ),
        migrations.AlterField(
            model_name='contactonormalizado',
            name='calle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='normalizador.Calle'),
        ),
        migrations.AlterField(
            model_name='contactonormalizado',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactonormalizado',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='normalizador.Provincia'),
        ),
    ]
