# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-13 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0009_contactonormalizado_localidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.IntegerField()),
                ('nombre_completo', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=6)),
                ('numero_documento', models.IntegerField()),
                ('telefono', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('altura', models.CharField(max_length=10)),
                ('barrio', models.CharField(max_length=50)),
                ('codigo_postal', models.IntegerField()),
                ('parcela', models.CharField(max_length=10)),
                ('ss', models.CharField(max_length=10)),
                ('ss_gs', models.CharField(max_length=10)),
                ('emi', models.CharField(max_length=10)),
                ('cualidad', models.IntegerField()),
                ('inhumados', models.CharField(max_length=4)),
                ('parcela_inhumados', models.IntegerField()),
                ('meses_deuda', models.IntegerField()),
                ('monto_deuda', models.DecimalField(decimal_places=2, max_digits=20)),
                ('productos', models.CharField(max_length=100)),
            ],
        ),
    ]
