# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-13 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0010_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo_cliente',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.IntegerField(db_index=True),
        ),
    ]
