# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-03 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('normalizador', '0028_auto_20181103_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleHojaRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=2)),
                ('tipo', models.IntegerField(blank=True, default=0, null=True)),
                ('titular', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HojaRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_hoja', models.CharField(db_index=True, max_length=8)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normalizador.Barrio')),
            ],
        ),
        migrations.AddField(
            model_name='detallehojaruta',
            name='hoja_ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoja_ruta.HojaRuta'),
        ),
    ]
