# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-03 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0028_auto_20181103_2151'),
        ('hoja_ruta', '0002_numerohojarruta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hojaruta',
            old_name='numero_hoja',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='hojaruta',
            name='barrio',
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='calle_barrio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='normalizador.CallesBarrio'),
            preserve_default=False,
        ),
    ]
