# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-06 23:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoja_ruta', '0003_auto_20181103_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialHojaRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='historial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hoja_ruta.HistorialHojaRuta'),
            preserve_default=False,
        ),
    ]
