# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-07 01:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoja_ruta', '0005_auto_20181107_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaruta',
            name='asiganda_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Sin Asignar'), (2, 'Esperando Devolucion'), (3, 'Cerrada')], default=1),
        ),
    ]
