# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-07 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_ruta', '0007_auto_20181107_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaruta',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Sin Asignar'), (2, 'Asignada'), (3, 'Cerrada')], default=1),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hojas_ruta', to='hoja_ruta.HistorialHojaRuta'),
        ),
    ]
