# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-07 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0028_auto_20181103_2151'),
        ('hoja_ruta', '0008_auto_20181107_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialhojaruta',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='normalizador.Barrio'),
            preserve_default=False,
        ),
    ]
