# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-10 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_ruta', '0012_auto_20181107_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallehojaruta',
            name='hoja_ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_hoja_ruta', to='hoja_ruta.HojaRuta'),
        ),
    ]
