# Generated by Django 2.0.7 on 2018-07-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=127, unique=True)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], db_index=True)),
            ],
        ),
    ]
