# Generated by Django 2.0.7 on 2018-07-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=127)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normalizador.Provincia')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='localidad',
            unique_together={('nombre', 'provincia')},
        ),
    ]
