# Generated by Django 2.0.7 on 2018-07-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0002_auto_20180721_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=127)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], db_index=True, default=1)),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='cuadrante',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normalizador.Localidad'),
        ),
        migrations.AlterUniqueTogether(
            name='cuadrante',
            unique_together={('nombre', 'localidad')},
        ),
    ]
