# Generated by Django 2.0.7 on 2018-07-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0004_auto_20180721_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='codigo_postal',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
