# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0007_auto_20180728_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=127)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], db_index=True, default=1)),
            ],
        ),
    ]
