# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0008_calle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallesBarrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura_desde', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('altura_hasta', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('referencia', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('plano', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('ubicacion', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('nomenclado', models.BooleanField(default=False)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normalizador.Barrio')),
                ('calle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normalizador.Calle')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='callesbarrio',
            unique_together=set([('barrio', 'calle')]),
        ),
    ]
