# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0013_titular'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroBarrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.IntegerField()),
                ('parentesis_abierto', models.BooleanField(default=False)),
                ('criterio', models.IntegerField()),
                ('valor', models.CharField(max_length=255)),
                ('parentesis_cerrado', models.BooleanField(default=False)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normalizador.Barrio')),
            ],
        ),
    ]
