# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0014_filtrobarrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtrobarrio',
            name='criterio',
            field=models.IntegerField(choices=[(1, 'Like'), (2, 'Not Like'), (3, '='), (4, '<>')]),
        ),
        migrations.AlterField(
            model_name='filtrobarrio',
            name='operador',
            field=models.IntegerField(choices=[(0, 'OR'), (1, 'AND')]),
        ),
    ]
