# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0015_auto_20180823_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiccionarioBarrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50)),
                ('actualizado', models.BooleanField(db_index=True, default=False)),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='normalizador.Barrio')),
            ],
        ),
    ]
