# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0017_criterio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtrobarrio',
            name='criterio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='normalizador.Criterio'),
        ),
    ]
