# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0018_auto_20180823_0136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Titular',
        ),
    ]
