# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0019_delete_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diccionariobarrio',
            name='nombre',
            field=models.CharField(db_index=True, max_length=127),
        ),
    ]
