# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0020_auto_20180824_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diccionariobarrio',
            name='actualizado',
        ),
    ]
