# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-25 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0021_remove_diccionariobarrio_actualizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiccionarioCalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='FiltroCalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.IntegerField(choices=[(0, 'OR'), (1, 'AND')])),
                ('parentesis_abierto', models.BooleanField(default=False)),
                ('valor', models.CharField(max_length=255)),
                ('parentesis_cerrado', models.BooleanField(default=False)),
                ('calle_barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normalizador.CallesBarrio')),
                ('criterio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='normalizador.Criterio')),
            ],
        ),
    ]
