# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-25 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0023_calleincorrecta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diccionariocalle',
            name='nombre',
        ),
        migrations.AddField(
            model_name='diccionariocalle',
            name='calle_barrio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='normalizador.CallesBarrio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diccionariocalle',
            name='calle_incorrecta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='normalizador.CalleIncorrecta'),
            preserve_default=False,
        ),
    ]
