# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-26 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0024_auto_20180825_0115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diccionariocalle',
            unique_together=set([('calle_incorrecta', 'calle_barrio')]),
        ),
    ]
