# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-18 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0026_auto_20180912_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='callesbarrio',
            name='tipo_numeracion',
            field=models.IntegerField(choices=[(1, 'Par'), (2, 'Impar'), (3, 'Todas las numeraciones')], db_index=True, default=3),
        ),
    ]
