# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-03 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normalizador', '0027_callesbarrio_tipo_numeracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallehojaruta',
            name='hoja_ruta',
        ),
        migrations.RemoveField(
            model_name='hojaruta',
            name='barrio',
        ),
        migrations.DeleteModel(
            name='DetalleHojaRuta',
        ),
        migrations.DeleteModel(
            name='HojaRuta',
        ),
    ]
