from normalizador.models.diccionario_barrio import DiccionarioBarrio
from normalizador.models.calle_incorrecta import CalleIncorrecta
from normalizador.models.criterio import Criterio
from normalizador.models.diccionario_calle import DiccionarioCalle
from normalizador.models.filtro_calle import FiltroCalle